spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/data_jpa
    username: postgres
    password: " "
    driver-class-name: org.postgresql.Driver
  jpa:
      hibernate:
        ddl-auto: create-drop
      database: postgresql
      showsql: true
